<a href="https://colab.research.google.com/github/GAO65/NLP_Ref/blob/main/FNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np
def Sigmoid(x):
  return 1/(1+np.exp(-x))

class Network(object):
  # shape_size is a list which contains elemnts of in each layer, 
  # and the lenth of the list is the num of the layers. 
  def __init__(self, shape_size):  
    self.num_layers = len(shape_size)
    self.shape_size = shape_size
    for x, y in zip(shape_size[:-1], shape_size[1:]):
      self.weights = [np.random.randn(x, y)]
    for y in shape_size[1:]:
      self.biases = [np.random.randn(y, 1)]
  def feedfoward(self, in_vec):
    for w, b in zip(self.weights, self.biases):
      out = Sigmoid(np.dot(in_vec, self.weights)+self.biases)
    return out

l = [2,3,2]
a = Network(l)
in_vec = [[1, 0, 1],[1,1,0]] 
print(a.feedfoward(in_vec))


[[[0.39861719 0.87922697]
  [0.468222   0.9062834 ]]

 [[0.04939569 0.44497878]
  [0.06456808 0.5157365 ]]]


In [25]:
import numpy as np
a = [1, 2, 3, 4]
print(a[:-1])
print(a[1:])
for x, y in zip(a[:-1], a[1:]):
  print(x, y)
  b = np.random.randn(x, y)
for y in zip(a[1:]):
  print(y)
  # c = np.random.randn(y, 1)
print(b)
# print(c)
d = np.random.randn(3, 1)
print(d)

[1, 2, 3]
[2, 3, 4]
1 2
2 3
3 4
(2,)
(3,)
(4,)
[[ 0.74403869  2.37538609  0.98771416  0.76220731]
 [-1.13639278 -0.18202708 -0.65170929 -0.27931705]
 [-0.16254065  1.63577838  0.15197873 -0.92947833]]
[[-0.00970758]
 [ 0.03080243]
 [-0.8554993 ]]
